services:
  apsu-game:
    build:
      context: .
      dockerfile: Dockerfile
    image: apsu-game:0.2.0-SNAPSHOT
    container_name: apsu-game-app
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - LIBGL_ALWAYS_SOFTWARE=${LIBGL_ALWAYS_SOFTWARE:-1}
    volumes:
      - ${X11_SOCKET_DIR:-/tmp/.X11-unix}:/tmp/.X11-unix:rw
